# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dqn_scheduler.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'dqn_scheduler.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64qn_scheduler.proto\x12\rdqn_scheduler\"\x96\x01\n\x08GPUState\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12\x11\n\ttotal_mem\x18\x03 \x01(\r\x12\x10\n\x08used_mem\x18\x04 \x01(\r\x12\x11\n\tused_core\x18\x05 \x01(\r\x12\x10\n\x08used_num\x18\x06 \x01(\r\x12\x0e\n\x06number\x18\x07 \x01(\r\x12\x13\n\x0b\x64\x65vice_type\x18\x08 \x01(\t\"\xa4\x01\n\x0ePredictRequest\x12\x11\n\tnode_name\x18\x01 \x01(\t\x12\x15\n\rpod_namespace\x18\x02 \x01(\t\x12\x10\n\x08pod_name\x18\x03 \x01(\t\x12\x0f\n\x07mem_req\x18\x04 \x01(\r\x12\x10\n\x08\x63ore_req\x18\x05 \x01(\r\x12\x0c\n\x04nums\x18\x06 \x01(\x05\x12%\n\x04gpus\x18\x07 \x03(\x0b\x32\x17.dqn_scheduler.GPUState\"5\n\x08GPUScore\x12\r\n\x05index\x18\x01 \x01(\x05\x12\r\n\x05score\x18\x02 \x01(\x01\x12\x0b\n\x03\x66it\x18\x03 \x01(\x08\"\x8d\x01\n\x0fPredictResponse\x12\x17\n\x0fordered_indexes\x18\x01 \x03(\x05\x12\x16\n\x0eselected_index\x18\x02 \x01(\x05\x12\'\n\x06scores\x18\x03 \x03(\x0b\x32\x17.dqn_scheduler.GPUScore\x12\x10\n\x08\x66\x61llback\x18\x04 \x01(\x08\x12\x0e\n\x06reason\x18\x05 \x01(\t2X\n\x0c\x44QNScheduler\x12H\n\x07Predict\x12\x1d.dqn_scheduler.PredictRequest\x1a\x1e.dqn_scheduler.PredictResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dqn_scheduler_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GPUSTATE']._serialized_start=39
  _globals['_GPUSTATE']._serialized_end=189
  _globals['_PREDICTREQUEST']._serialized_start=192
  _globals['_PREDICTREQUEST']._serialized_end=356
  _globals['_GPUSCORE']._serialized_start=358
  _globals['_GPUSCORE']._serialized_end=411
  _globals['_PREDICTRESPONSE']._serialized_start=414
  _globals['_PREDICTRESPONSE']._serialized_end=555
  _globals['_DQNSCHEDULER']._serialized_start=557
  _globals['_DQNSCHEDULER']._serialized_end=645
# @@protoc_insertion_point(module_scope)
