# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scheduler.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'scheduler.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fscheduler.proto\x12\rdqn_inference\"Z\n\x08TaskInfo\x12\x0f\n\x07task_id\x18\x01 \x01(\x05\x12\x12\n\ncpu_demand\x18\x02 \x01(\x02\x12\x15\n\rmemory_demand\x18\x03 \x01(\x02\x12\x12\n\ngpu_demand\x18\x04 \x01(\x02\"\x87\x01\n\x08NodeInfo\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\x12\x10\n\x08\x63puUsage\x18\x02 \x01(\x02\x12\x13\n\x0bmemoryUsage\x18\x03 \x01(\x02\x12\x10\n\x08gpuUsage\x18\x04 \x01(\x02\x12\x0e\n\x06\x63puRem\x18\x05 \x01(\x02\x12\x11\n\tmemoryRem\x18\x06 \x01(\x02\x12\x0e\n\x06gpuRem\x18\x07 \x01(\x02\"g\n\x15\x42\x61tchInferenceRequest\x12&\n\x05nodes\x18\x01 \x03(\x0b\x32\x17.dqn_inference.NodeInfo\x12&\n\x05tasks\x18\x02 \x03(\x0b\x32\x17.dqn_inference.TaskInfo\"9\n\x13\x42\x61tchInferenceReply\x12\x10\n\x08task_ids\x18\x01 \x03(\x05\x12\x10\n\x08node_ids\x18\x02 \x03(\x05\x32\x66\n\nDQNService\x12X\n\x0cPredictBatch\x12$.dqn_inference.BatchInferenceRequest\x1a\".dqn_inference.BatchInferenceReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scheduler_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKINFO']._serialized_start=34
  _globals['_TASKINFO']._serialized_end=124
  _globals['_NODEINFO']._serialized_start=127
  _globals['_NODEINFO']._serialized_end=262
  _globals['_BATCHINFERENCEREQUEST']._serialized_start=264
  _globals['_BATCHINFERENCEREQUEST']._serialized_end=367
  _globals['_BATCHINFERENCEREPLY']._serialized_start=369
  _globals['_BATCHINFERENCEREPLY']._serialized_end=426
  _globals['_DQNSERVICE']._serialized_start=428
  _globals['_DQNSERVICE']._serialized_end=530
# @@protoc_insertion_point(module_scope)
